baseurl = "/"
title = "papadope"
theme = "hello-friend-ng"

[Params]
    mainSections = ["/"]
    intro = true
    headline = "Papadope"
    description = "WriteUps & Walkthroughs"
    github = "https://github.com/papadope"
    email = "xristos8170@gmail.com"
    opengraph = true
    shareTwitter = false
    shareGithub = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/"
    
[[menu.main]]
    identifier = "thm"
    name = "THM"
    url = "/thm/"

[[menu.main]]
    identifier = "htb"
    name = "HTB"
    url = "/htb/"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
